name: Tengeneza APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Fungua kodi zako
      uses: actions/checkout@v4

    - name: Weka Java 17
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Tengeneza APK kwa kutumia Gradle ya Mfumo
      run: |
        if [ -f "./gradlew" ]; then
          chmod +x gradlew
          ./gradlew assembleDebug
        else
          gradle assembleDebug || gradle build
        fi

    - name: Pakia APK (Upload APK)
      uses: actions/upload-artifact@v4
      with:
        name: app-debug
        path: "**/build/outputs/apk/debug/*.apk"
