name: Tengeneza APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Fungua kodi zako
      uses: actions/checkout@v4

    - name: Weka Java 17
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Ruhusu Gradle Iendesheke
      run: chmod +x gradlew || true

    - name: Tengeneza APK (Build APK)
      run: ./gradlew assembleDebug || ./gradlew build
